LANG_PAIRS = [
  ('az', u"Azərbaycanca"),
  ('en', u"English"),
  ('ru', u"Русский"),
  ('uz', u"Oʻzbekcha"),
  ('es', u"Español"),
  ('id', u"Indonesian"),
  ('it', u"Italiano"),
  ('uk', u"Українська"),
  ('pt', u"Português"),
  ('tr', u"Türkçe"),
  ('fa', u"فارسی"),
  ('de', u"Deutsch"),
  ('fr', u"Français"),
  ('nl', u"Nederlands"),
  ('kz', u"Қазақ"),
  ('az', u"Azərbaycan dili"),
  ('ro', u"Română"),
  ('hi', u"हिन्दी"),
  ('hing', u"Hinglish"),
  ('ckb', u"کوردی")
]
